// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySignalFormat(arg1) {
  return window['go']['main']['App']['ApplySignalFormat'](arg1);
}

export function ConnectMeter(arg1, arg2) {
  return window['go']['main']['App']['ConnectMeter'](arg1, arg2);
}

export function ConnectProjector(arg1, arg2) {
  return window['go']['main']['App']['ConnectProjector'](arg1, arg2);
}

export function ConnectTransport(arg1, arg2) {
  return window['go']['main']['App']['ConnectTransport'](arg1, arg2);
}

export function CurrentSignalFormat() {
  return window['go']['main']['App']['CurrentSignalFormat']();
}

export function DisconnectMeter() {
  return window['go']['main']['App']['DisconnectMeter']();
}

export function DisconnectProjector() {
  return window['go']['main']['App']['DisconnectProjector']();
}

export function DisconnectTransport() {
  return window['go']['main']['App']['DisconnectTransport']();
}

export function EvaluateMeasurement(arg1, arg2) {
  return window['go']['main']['App']['EvaluateMeasurement'](arg1, arg2);
}

export function GetActivePattern() {
  return window['go']['main']['App']['GetActivePattern']();
}

export function GetCalibrationStandards() {
  return window['go']['main']['App']['GetCalibrationStandards']();
}

export function GetCalibrationSteps(arg1) {
  return window['go']['main']['App']['GetCalibrationSteps'](arg1);
}

export function GetDisplayEDID(arg1) {
  return window['go']['main']['App']['GetDisplayEDID'](arg1);
}

export function GetPatternBattery() {
  return window['go']['main']['App']['GetPatternBattery']();
}

export function GetPatternDisplay() {
  return window['go']['main']['App']['GetPatternDisplay']();
}

export function GetProjectorCapabilities() {
  return window['go']['main']['App']['GetProjectorCapabilities']();
}

export function GetProjectorControl(arg1) {
  return window['go']['main']['App']['GetProjectorControl'](arg1);
}

export function GetSignalFormats() {
  return window['go']['main']['App']['GetSignalFormats']();
}

export function ListDisplays() {
  return window['go']['main']['App']['ListDisplays']();
}

export function ListMeterDrivers() {
  return window['go']['main']['App']['ListMeterDrivers']();
}

export function ListProjectorDrivers() {
  return window['go']['main']['App']['ListProjectorDrivers']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListTransportDrivers() {
  return window['go']['main']['App']['ListTransportDrivers']();
}

export function Measure() {
  return window['go']['main']['App']['Measure']();
}

export function SetActivePattern(arg1) {
  return window['go']['main']['App']['SetActivePattern'](arg1);
}

export function SetPatternDisplay(arg1) {
  return window['go']['main']['App']['SetPatternDisplay'](arg1);
}

export function SetProjectorControl(arg1, arg2) {
  return window['go']['main']['App']['SetProjectorControl'](arg1, arg2);
}
