// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transport} from '../models';
import {pattern} from '../models';
import {display} from '../models';
import {projector} from '../models';
import {meter} from '../models';

export function ApplySignalFormat(arg1:transport.SignalFormat):Promise<void>;

export function ConnectMeter(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ConnectProjector(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ConnectTransport(arg1:string,arg2:Record<string, any>):Promise<void>;

export function CurrentSignalFormat():Promise<transport.SignalFormat>;

export function DisconnectMeter():Promise<void>;

export function DisconnectProjector():Promise<void>;

export function DisconnectTransport():Promise<void>;

export function GetActivePattern():Promise<pattern.Pattern>;

export function GetDisplayEDID(arg1:string):Promise<display.EDID>;

export function GetPatternBattery():Promise<Array<pattern.Pattern>>;

export function GetPatternDisplay():Promise<string>;

export function GetProjectorCapabilities():Promise<projector.Capabilities>;

export function GetProjectorControl(arg1:string):Promise<any>;

export function GetSignalFormats():Promise<Array<transport.SignalFormat>>;

export function ListDisplays():Promise<Array<display.Output>>;

export function ListMeterDrivers():Promise<Array<string>>;

export function ListProjectorDrivers():Promise<Array<string>>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListTransportDrivers():Promise<Array<string>>;

export function Measure():Promise<meter.Reading>;

export function SetActivePattern(arg1:pattern.Pattern):Promise<void>;

export function SetPatternDisplay(arg1:string):Promise<void>;

export function SetProjectorControl(arg1:string,arg2:any):Promise<void>;
