// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySignalFormat(arg1) {
  return window['go']['main']['App']['ApplySignalFormat'](arg1);
}

export function ConnectMeter(arg1, arg2) {
  return window['go']['main']['App']['ConnectMeter'](arg1, arg2);
}

export function ConnectProjector(arg1, arg2) {
  return window['go']['main']['App']['ConnectProjector'](arg1, arg2);
}

export function ConnectTransport(arg1, arg2) {
  return window['go']['main']['App']['ConnectTransport'](arg1, arg2);
}

export function CurrentSignalFormat() {
  return window['go']['main']['App']['CurrentSignalFormat']();
}

export function DisconnectMeter() {
  return window['go']['main']['App']['DisconnectMeter']();
}

export function DisconnectProjector() {
  return window['go']['main']['App']['DisconnectProjector']();
}

export function DisconnectTransport() {
  return window['go']['main']['App']['DisconnectTransport']();
}

export function GetProjectorCapabilities() {
  return window['go']['main']['App']['GetProjectorCapabilities']();
}

export function GetProjectorControl(arg1) {
  return window['go']['main']['App']['GetProjectorControl'](arg1);
}

export function GetSignalFormats() {
  return window['go']['main']['App']['GetSignalFormats']();
}

export function ListMeterDrivers() {
  return window['go']['main']['App']['ListMeterDrivers']();
}

export function ListProjectorDrivers() {
  return window['go']['main']['App']['ListProjectorDrivers']();
}

export function ListTransportDrivers() {
  return window['go']['main']['App']['ListTransportDrivers']();
}

export function Measure() {
  return window['go']['main']['App']['Measure']();
}

export function SetProjectorControl(arg1, arg2) {
  return window['go']['main']['App']['SetProjectorControl'](arg1, arg2);
}
